[package]
authors = ["Band Protocol <connect@bandprotocol.com>"]
description = "Oracle script VM runtime"
edition = "2021"
license = "Apache-2.0"
name = "owasm-vm"
readme = "README.md"
repository = "https://github.com/bandprotocol/owasm/tree/master/packages/vm"
version = "0.2.1"

[dependencies]
assert_matches = "1.3.0"
clru = "0.2.0"
hex = "0.4"
owasm-crypto = {path = "../crypto", version = "0.2.1"}
sha2 = "0.9.1"
tempfile = "3.1.0"
wasm-instrument = "0.2.0"
wasmer = {version = "2.3.0", default-features = false, features = ["singlepass", "compiler", "universal"]}
wasmer-middlewares = "2.3.0"
