[package]
authors = ["Band Protocol <connect@bandprotocol.com>"]
description = "Oracle script VM runtime"
edition = "2018"
license = "Apache-2.0"
name = "owasm-vm"
readme = "README.md"
repository = "https://github.com/bandprotocol/owasm/tree/master/packages/vm"
version = "0.1.13"

[dependencies]
assert_matches = "1.3.0"
clru = "0.2.0"
cosmwasm-vm = "0.13.2"
hex = "0.4"
parity-wasm = "0.41"
pwasm-utils = "0.12"
tempfile = "3.1.0"
wasmer = {version = "1.0.2", default-features = false, features = ["jit", "singlepass", "compiler"]}
