[package]
name = "owasm"
version = "0.1.7"
authors = ["Band Protocol <connect@bandprotocol.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/bandprotocol/bandchain/tree/master/owasm"
description = """
TODO
"""

[dependencies]
json = "0.12.0"
num = "*"
