[package]
name = "owasm"
version = "0.1.7"
authors = ["Band Protocol <connect@bandprotocol.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/bandprotocol/d3n/tree/master/owasm"
description = """
TODO
"""

[dependencies]
serde = { version = "1.0.103", features = ["derive"] }
serde_json = "1.0"
json = "0.12.0"

[workspace]
members = [
    "exec",
    "parser",
    "examples/alphavantage",
    "examples/binance_price",
    "examples/coingecko_price",
    "examples/coingecko_volume",
    "examples/cryptocompare_price",
    "examples/cryptocompare_volume",
    "examples/ethereum_gas_price",
    "examples/yahoo_price",
    "examples/bitcoin_info",
    "examples/weather_info",
    "examples/flight_verification",
    "examples/random_u64",
    "chaintests/crypto_price",
    "chaintests/main",
    "chaintests/silly",
]
