[package]
name = "exec"
version = "0.1.0"
authors = ["Band Protocol <connect@bandprotocol.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer-runtime = "0.8.0"
owasm = { path = ".." }
