[package]
authors = ["Band Protocol <connect@bandprotocol.com>"]
description = "Standard library for oracle scripts on BandChain"
edition = "2018"
license = "Apache-2.0"
name = "owasm-kit"
readme = "README.md"
repository = "https://github.com/bandprotocol/owasm/tree/master/packages/kit"
version = "0.2.3"

[dependencies]
num = "0.4.0"
