[package]
authors = ["Band Protocol <connect@bandprotocol.com>"]
description = "Cryoto functions for Oracle script"
edition = "2018"
license = "Apache-2.0"
name = "owasm-crypto"
readme = "README.md"
repository = "https://github.com/bandprotocol/owasm/tree/master/packages/crypto"
version = "0.2.2"

[features]
default = []
# backtraces provides much better context at runtime errors (in non-wasm code)
# at the cost of a bit of code size and performance.
# This feature requires Rust nightly because it depends on the unstable backtrace feature.
backtraces = []

[dependencies]
hex = "0.4.3"
lazy_static = "1.4.0"
rust-gmp = "0.5.0"
sha2 = "0.9.5"
thiserror = "1.0"
