name: Owasm Workflow
on: [push, pull_request]

jobs:
  wasm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v2

      - name: Install Rust and rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Check cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-owasm-${{ hashFiles('**/Cargo.lock') }}

      - name: Run owasm tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path Cargo.toml --all
